const express = require("express");
const router = express.Router();
//所有员工
router.get("/", (req, res) => {
  // console.log(req.body)
  res.json({
    code: 200,
    data: {
      message: "success",
      list:  [
        {
          key: "1",
          name: "John Brown",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售一部",
          position: "销售经理",
          entryTime: "2012-05-22",
          workingYears: "4",
        },
        {
          key: "2",
          name: "Jim Green",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售二部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "3",
          name: "Joe Black",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售三部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "4",
          name: "John Brown",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售一部",
          position: "销售经理",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "5",
          name: "Jim Green",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售二部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "6",
          name: "Joe Black",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售三部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "7",
          name: "John Brown",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售一部",
          position: "销售经理",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "8",
          name: "Jim Green",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售二部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "9",
          name: "Joe Black",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售三部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "10",
          name: "John Brown",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售一部",
          position: "销售经理",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "11",
          name: "Jim Green",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售二部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "12",
          name: "Joe Black",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售三部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "13",
          name: "John Brown",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售一部",
          position: "销售经理",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "14",
          name: "Jim Green",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售二部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "15",
          name: "Joe Black",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售三部",
          position: "市场专员",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
        {
          key: "16",
          name: "John Brown",
          phoneNum: "13300009999",
          sex: "男",
          Department: "销售一部",
          position: "销售经理",
          entryTime: "2016-05-22",
          workingYears: "4",
        },
      ]
    },
  });
});
router.get("/trainingSignIn", (req, res) => {
    // console.log(req.body)
    res.json({
      code: 200,
      data: {
        message: "success",
        list: [
            {
              key: "1",
              name: "John Brown",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售一部",
              position: "销售经理",
            },
            {
              key: "2",
              name: "Jim Green",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售二部",
              position: "市场专员",
            },
            {
              key: "3",
              name: "Joe Black",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售三部",
              position: "市场专员",
            },
            {
              key: "4",
              name: "John Brown",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售一部",
              position: "销售经理",
            },
            {
              key: "5",
              name: "Jim Green",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售二部",
              position: "市场专员",
            },
            {
              key: "6",
              name: "Joe Black",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售三部",
              position: "市场专员",
            },
            {
              key: "7",
              name: "John Brown",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售一部",
              position: "销售经理",
            },
            {
              key: "8",
              name: "Jim Green",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售二部",
              position: "市场专员",
            },
            {
              key: "9",
              name: "Joe Black",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售三部",
              position: "市场专员",
            },
            {
              key: "10",
              name: "John Brown",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售一部",
              position: "销售经理",
            },
            {
              key: "11",
              name: "Jim Green",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售二部",
              position: "市场专员",
            },
            {
              key: "12",
              name: "Joe Black",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售三部",
              position: "市场专员",
            },
            {
              key: "13",
              name: "John Brown",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售一部",
              position: "销售经理",
            },
            {
              key: "14",
              name: "Jim Green",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售二部",
              position: "市场专员",
            },
            {
              key: "15",
              name: "Joe Black",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售三部",
              position: "市场专员",
            },
            {
              key: "16",
              name: "John Brown",
              CheckInTime: "15:37",
              TrainingLocation: "会议室",
              Department: "销售一部",
              position: "销售经理",
            },
          ] 
      },
    });
  });
module.exports = router;